apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: nbm5hx6yp-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nbm5hx6yp-go 
  name: nbm5hx6yp-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: nbm5hx6yp-go 
